config/routes.rb
Rails.application.routes.draw do
  resources :instruments

  resources :musicians

   root 'musicians#index'

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
	 has_many :musicians
end

app/models/musician.rb
class Musician < ActiveRecord::Base
   belongs_to :instrument
   geocoded_by :address
   after_validation :geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:instrument_name)
    end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  before_action :set_musician, only: [:show, :edit, :update, :destroy]

  # GET /musicians
  # GET /musicians.json
  #PARA MAS INFO SIGUE MI TUTORIAL QUE VIENE CON EL PASO A PASO DE TODO ESTE CODIGO:
  #http://danielagattoni.quiltyweb.com/streetmusicmap-parte-2-integracion-gmaps4rails/
  def index
    @musicians = Musician.all
    @hash = Gmaps4rails.build_markers(@musicians) do |musician, marker|
      marker.lat musician.latitude
      marker.lng musician.longitude
      marker.infowindow "<div class='box' style='width:200px;'><h4><strong>"+musician.musician_name+", "+musician.instrument.instrument_name+"</strong></h4><img src='http://img.youtube.com/vi/"+musician.youtube_video+"/mqdefault.jpg' width='111' height='90' class=''></div>"
    end
  end

  # GET /musicians/1
  # GET /musicians/1.json
  def show
  end

  # GET /musicians/new
  def new
    @musician = Musician.new
    @instruments = Instrument.all
  end

  # GET /musicians/1/edit
  def edit
       @instruments = Instrument.all
  end

  # POST /musicians
  # POST /musicians.json
  def create
    @musician = Musician.new(musician_params)

    respond_to do |format|
      if @musician.save
        format.html { redirect_to @musician, notice: 'Musician was successfully created.' }
        format.json { render :show, status: :created, location: @musician }
      else
        format.html { render :new }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musicians/1
  # PATCH/PUT /musicians/1.json
  def update
    respond_to do |format|
      if @musician.update(musician_params)
        format.html { redirect_to @musician, notice: 'Musician was successfully updated.' }
        format.json { render :show, status: :ok, location: @musician }
      else
        format.html { render :edit }
        format.json { render json: @musician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicians/1
  # DELETE /musicians/1.json
  def destroy
    @musician.destroy
    respond_to do |format|
      format.html { redirect_to musicians_url, notice: 'Musician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musician
      @musician = Musician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musician_params
      params.require(:musician).permit(:latitude, :longitude, :youtube_video, :twitter, :facebook, :address, :description, :musician_name, :instrument_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/views/instruments/_form.html.erb
<%= form_for(@instrument) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :instrument_name %><br>
    <%= f.text_field :instrument_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<h1>Listing instruments</h1>

<table>
  <thead>
    <tr>
      <th>Instrument name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instruments.each do |instrument| %>
      <tr>
        <td><%= instrument.instrument_name %></td>
        <td><%= link_to 'Show', instrument %></td>
        <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
        <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instrument', new_instrument_path %>

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Instrument name:</strong>
  <%= @instrument.instrument_name %>
</p>

<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<%= link_to 'Back', instruments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="http://getbootstrap.com/favicon.ico">

  <!-- bootstrap -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  <!-- google maps tienes que conseguir tu prpia api key y pegarla en key=XXXXX -->
  <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry&amp;key=XXXXX">
  </script>

  <!-- Custom styles for this template  -->
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


</head>
<body>

  <%= yield %>

</body>
</html>

app/views/musicians/_form.html.erb
<%= form_for(@musician) do |f| %>
  <% if @musician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@musician.errors.count, "error") %> prohibited this musician from being saved:</h2>

      <ul>
      <% @musician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :youtube_video %><br>
    <%= f.text_field :youtube_video %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :musician_name %><br>
    <%= f.text_field :musician_name %>
  </div>
  <div class="field">
    <%= f.label :instrument_id %><br>
 
    <%= collection_select(:musician, :instrument_id, @instruments, :id, :instrument_name, prompt: true) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musicians/edit.html.erb
<h1>Editing musician</h1>

<%= render 'form' %>
 

<%= link_to 'Show', @musician %> |
<%= link_to 'Back', musicians_path %>

app/views/musicians/index.html.erb
  <!-- contenedor del mapa -->
   <div class="site-wrapper">     
    <div  id="map" class="site-wrapper-inner">
      <div  class="cover-container">
        
     </div>
   </div>
 </div>
 <!--//fin contenedor mapa-->


<!-- footer -->
 <div class="container-fluid">
  <div class="row">
    <div class=" col-lg-12 mastfoot">
      <div class="inner">
        <p>street music map <%= link_to 'New Musician', new_musician_path %> </p>        
<%=raw @hash.to_json %>
      </div>
    </div>
  </div>
</div>
<!-- //fin footer-->

<!-- inicio de mi script que dibuja el mapa-->
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>
<!-- //fin script-->

 <!--  
 PARA MAS INFO SIGUE MI TUTORIAL QUE VIENE CON EL PASO A PASO DE TODO ESTE CODIGO:
 http://danielagattoni.quiltyweb.com/streetmusicmap-parte-2-integracion-gmaps4rails/ 
 -->

app/views/musicians/new.html.erb
<h1>New musician</h1>

<%= render 'form' %>


<%= link_to 'Back', musicians_path %>

app/views/musicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @musician.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @musician.longitude %>
</p>

<p>
  <strong>Youtube video:</strong>
  <%= @musician.youtube_video %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @musician.twitter %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @musician.facebook %>
</p>

<p>
  <strong>Address:</strong>
  <%= @musician.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @musician.description %>
</p>

<p>
  <strong>Musician name:</strong>
  <%= @musician.musician_name %>
</p>

<p>
  <strong>Instrument:</strong>
  
  <%= @musician.instrument.instrument_name %>
</p>

<%= link_to 'Edit', edit_musician_path(@musician) %> |
<%= link_to 'Back', musicians_path %>